[package]
name = "template"
version = "0.1.0"
authors = ["nn <nn@nn.nn>"]

[dependencies]
slack = { git = "https://github.com/dvarum12/slack-rs"}
slack_api = { git = "https://github.com/dvarum12/slack-rs-api" }

lazy_static = "*"
serde = "*"
serde_derive = "*"